#!/bin/bash

set -e

rm -rf tmp/game
mkdir -p tmp/game/{app,lib}
cp -r tests tmp/game/
cp -r support tmp/game/
cp dragonborn.rb tmp/game/lib
touch tmp/game/app/main.rb

for test in $(find tests -name test.rb); do
  ./dragonruby tmp/game --test "${test}"
done

echo "All tests passed!"
