name: "DragonRuby 5.29"
on:
  pull_request:
    paths-ignore:
      - '**.md'
  push:
    branches:
      - main

jobs:
  run-tests:
    uses: ./.github/workflows/regression-tests.yml
    with:
      version: '5.29'
