name: "5.32"
on:
  pull_request:
    paths-ignore:
      - '**.md'
  push:
    branches:
      - main

jobs:
  tests:
    uses: ./.github/workflows/regression-tests.yml
    with:
      version: '5.32'
