name: "Tests"

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string

jobs:
  test:
    strategy:
      matrix:
        runner:
          - windows-2022
          - macos-12
          - ubuntu-22.04
        tier:
          - standard
          - pro
      fail-fast: false
    runs-on: ${{ matrix.runner }}
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4
      - uses: kfischer-okarin/download-dragonruby@v1
        with:
          version: ${{ inputs.version }}
          license_tier: ${{ matrix.tier }}
      - name: Run tests
        env:
          SDL_VIDEODRIVER: dummy
          SDL_AUDIODRIVER: dummy
        run: scripts/test
